# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Run Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Start xcode build 🛠
        run: |
          xcodebuild clean test -project JLPT-Quiz/JLPT\ Quiz.xcodeproj -scheme JLPT-Quiz -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=latest'

      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Always Run
        if: always() # Pick up events even if the job fails or is canceled.
